/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as authAuthImport } from './routes/(auth)/_auth'
import { Route as authAuthUsersImport } from './routes/(auth)/_auth/users'
import { Route as authAuthProjectsImport } from './routes/(auth)/_auth/projects'
import { Route as authAuthDashboardImport } from './routes/(auth)/_auth/dashboard'

// Create Virtual Routes

const authImport = createFileRoute('/(auth)')()

// Create/Update Routes

const authRoute = authImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authAuthRoute = authAuthImport.update({
  id: '/_auth',
  getParentRoute: () => authRoute,
} as any)

const authAuthUsersRoute = authAuthUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => authAuthRoute,
} as any)

const authAuthProjectsRoute = authAuthProjectsImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => authAuthRoute,
} as any)

const authAuthDashboardRoute = authAuthDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authAuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authAuthImport
      parentRoute: typeof authRoute
    }
    '/(auth)/_auth/dashboard': {
      id: '/(auth)/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authAuthDashboardImport
      parentRoute: typeof authAuthImport
    }
    '/(auth)/_auth/projects': {
      id: '/(auth)/_auth/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof authAuthProjectsImport
      parentRoute: typeof authAuthImport
    }
    '/(auth)/_auth/users': {
      id: '/(auth)/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof authAuthUsersImport
      parentRoute: typeof authAuthImport
    }
  }
}

// Create and export the route tree

interface authAuthRouteChildren {
  authAuthDashboardRoute: typeof authAuthDashboardRoute
  authAuthProjectsRoute: typeof authAuthProjectsRoute
  authAuthUsersRoute: typeof authAuthUsersRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthDashboardRoute: authAuthDashboardRoute,
  authAuthProjectsRoute: authAuthProjectsRoute,
  authAuthUsersRoute: authAuthUsersRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface authRouteChildren {
  authAuthRoute: typeof authAuthRouteWithChildren
}

const authRouteChildren: authRouteChildren = {
  authAuthRoute: authAuthRouteWithChildren,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof authAuthRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof authAuthDashboardRoute
  '/projects': typeof authAuthProjectsRoute
  '/users': typeof authAuthUsersRoute
}

export interface FileRoutesByTo {
  '/': typeof authAuthRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof authAuthDashboardRoute
  '/projects': typeof authAuthProjectsRoute
  '/users': typeof authAuthUsersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/(auth)': typeof authRouteWithChildren
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(auth)/_auth/dashboard': typeof authAuthDashboardRoute
  '/(auth)/_auth/projects': typeof authAuthProjectsRoute
  '/(auth)/_auth/users': typeof authAuthUsersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/dashboard' | '/projects' | '/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dashboard' | '/projects' | '/users'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/(auth)'
    | '/(auth)/_auth'
    | '/(auth)/_auth/dashboard'
    | '/(auth)/_auth/projects'
    | '/(auth)/_auth/users'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  authRoute: typeof authRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  authRoute: authRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/(auth)"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/(auth)": {
      "filePath": "(auth)",
      "children": [
        "/(auth)/_auth"
      ]
    },
    "/(auth)/_auth": {
      "filePath": "(auth)/_auth.tsx",
      "parent": "/(auth)",
      "children": [
        "/(auth)/_auth/dashboard",
        "/(auth)/_auth/projects",
        "/(auth)/_auth/users"
      ]
    },
    "/(auth)/_auth/dashboard": {
      "filePath": "(auth)/_auth/dashboard.tsx",
      "parent": "/(auth)/_auth"
    },
    "/(auth)/_auth/projects": {
      "filePath": "(auth)/_auth/projects.tsx",
      "parent": "/(auth)/_auth"
    },
    "/(auth)/_auth/users": {
      "filePath": "(auth)/_auth/users.tsx",
      "parent": "/(auth)/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
